- hosts: $inv_hosts
  gather_facts: yes
  tasks:
  - name: Check the disk space
    shell: "df -h | awk {'print $5'}"
    register: result

  - debug: msg="{{result.stdout}}"

  - debug: msg="IP of the server {{ansible_default_ipv4.address}}"
    when: result|success

  - debug: msg="Mac address of the servet {{ansible_default_ipv4.macaddress}}"
